management:
  endpoint:
    env:
      enabled: true
    health:
      enabled: true
    liquibase:
      enabled: true
    logfile:
      enabled: true
    metrics:
      enabled: true
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: "*"